### ISSUE TITLE
Bug crash/auto close

### ISSUE THREAD

**Issue by QBGamer** [quangpao/auto_chat_game_tracker#1]
Tool some time crash or auto close, I don't see any ram or cpu problem!

**Comment by QBGamer** [comment]
When opening multiple accounts I guess

**Comment by quangpao** [comment]
Is opening many account lead to using the same log file or what? Can you give me further information ? @QBGamer

**Comment by QBGamer** [comment]
> Is opening many account lead to using the same log file or what? Can you give me further information ? @QBGamer

Sr crash when "Solve the following"/math thing no error found in log file!
